project(root VERSION 0.1.0)

set(CMAKE_CXX_STANDARD 14)
set(CMAKE_INCLUDE_CURRENT_DIR ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTORCC ON)

set(root_RESOURCES
  resources/root.qrc
)

add_library(root SHARED ${root_RESOURCES})

get_property(OUTPUT_PATH GLOBAL PROPERTY TARGET_DIR)
set(LIBRARY_OUTPUT_PATH ${OUTPUT_PATH}/plugins/${PROJECT_NAME})
file(COPY root.plugin DESTINATION ${LIBRARY_OUTPUT_PATH})
file(COPY root.py DESTINATION ${LIBRARY_OUTPUT_PATH})
file(COPY resources DESTINATION ${LIBRARY_OUTPUT_PATH})
